tunnel: discord-activity-tunnel
credentials-file: "C:\\Users\\Nathan Kipp\\.cloudflared\\0244f5c6-654f-4f47-b648-4abbd2e24855.json"

ingress:
  - hostname: nathankippportfolio.me
    service: http://localhost:5173
  - service: http_status:404